name: acomplus
description: "An Ecommerce Project"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  get: ^4.7.2
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/acomplus.png"
  min_sdk_android: 21

  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  assets:
    - asset/

